services:
  app-dev:
    image: satellite-pass-app:dev
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 80
      CONFIG_FILENAME: config_files/conf_test1
    ports:
      - "12346:80"
    build:
      context: .
      target: development
    # command: ["config_files/conf_test1"]
  

  app-prod:
    image: satellite-pass-app:prod
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 60
      CONFIG_FILENAME: 
    ports:
      - "12345:60"
      - "5000:60"
    build:
      context: .
      target: production
    # command: ["config_files/conf_default", "3", "60"]
